/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ###### API rror ###### <u>API Fehler</u>
 */
export interface ApiErrorDTO { 
    /**
     * ###### Error code ###### <u>Fehlercode</u>
     */
    code: string;
    /**
     * ###### Error message ###### <u>Fehlernachricht</u>
     */
    message: string;
}

