/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDataDTO } from './metaData.model';


/**
 * ###### Boolean attribute including value and meta data ###### <u>Boolean-Attribute inkl. Wert und Metadaten</u>
 */
export interface BooleanAttributeDTO { 
    value?: boolean | null;
    metadata: MetaDataDTO;
}

