/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationMetaDataDTO } from './validationMetaData.model';


/**
 * ###### Date meta data ###### <u>Date Metadaten</u>
 */
export interface DateMetaDataDTO { 
    /**
     * ###### Minimum date ###### <u>Minimales Datum</u>
     */
    min?: string;
    /**
     * ###### Maximum date ###### <u>Maximales Datum</u>
     */
    max?: string;
    validation?: ValidationMetaDataDTO;
    /**
     * ###### Required property ###### <u>Erforderliche Eigenschaft</u>
     */
    required?: boolean;
    /**
     * ###### Fixed property ###### <u>Unveränderliche Eigenschaft</u>
     */
    fixed?: boolean;
}

