/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateMetaDataDTO } from './dateMetaData.model';


export interface DateAttributeRequiredDTO { 
    /**
     * date
     */
    value: string;
    metadata: DateMetaDataDTO;
}

