/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateMetaDataDTO } from './dateMetaData.model';


/**
 * ###### Date attribute including value and meta data ###### <u>Datum-Attribute inkl. Wert und Metadaten</u>
 */
export interface DateAttributeDTO { 
    /**
     * date
     */
    value?: string | null;
    metadata: DateMetaDataDTO;
}

