/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DoubleMetaDataDTO } from './doubleMetaData.model';


/**
 * ###### Number attribute including value and meta data ###### <u>Number-Attribute inkl. Wert und Metadaten</u>
 */
export interface DoubleAttributeDTO { 
    value?: number | null;
    metadata: DoubleMetaDataDTO;
}

