/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationMetaDataDTO } from './validationMetaData.model';


/**
 * ###### Number meta data ###### <u>Number Metadaten</u>
 */
export interface DoubleMetaDataDTO { 
    /**
     * ###### Minimum ###### <u>Minimum</u>
     */
    min?: number;
    /**
     * ###### Maximum ###### <u>Maximum</u>
     */
    max?: number;
    validation?: ValidationMetaDataDTO;
    /**
     * ###### Required property ###### <u>Erforderliche Eigenschaft</u>
     */
    required?: boolean;
    /**
     * ###### Fixed property ###### <u>Unveränderliche Eigenschaft</u>
     */
    fixed?: boolean;
}

