/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntegerMetaDataDTO } from './integerMetaData.model';


/**
 * ###### Integer attribute including value and meta data ###### <u>Integer-Attribute inkl. Wert und Metadaten</u>
 */
export interface IntegerAttributeRequiredDTO { 
    value: number;
    metadata: IntegerMetaDataDTO;
}

