/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListItemMetaDataDTO } from './listItemMetaData.model';
import { ValidationMetaDataDTO } from './validationMetaData.model';


/**
 * ###### Metadata for list items ###### <u>Metadaten für Listenelemente</u>
 */
export interface ListMetaDataDTO { 
    /**
     * ###### All list items ###### <u>Alle Listenelmente</u>
     */
    options: Array<ListItemMetaDataDTO>;
    validation?: ValidationMetaDataDTO;
    /**
     * ###### Required property ###### <u>Erforderliche Eigenschaft</u>
     */
    required?: boolean;
    /**
     * ###### Fixed property ###### <u>Unveränderliche Eigenschaft</u>
     */
    fixed?: boolean;
}

