/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListItemMetaDataDTO } from './listItemMetaData.model';
import { ListMetaDataDTO } from './listMetaData.model';


/**
 * ###### List attribute including value and meta data ###### <u>List-Attribute inkl. Wert und Metadaten</u>
 */
export interface ListAttributeRequiredDTO { 
    selectedOption: ListItemMetaDataDTO;
    metadata: ListMetaDataDTO;
}

