/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ###### Metadata for a list item ###### <u>Metadaten für ein Listenelement</u>
 */
export interface ListItemMetaDataDTO { 
    /**
     * ###### List item value ###### <u>Wert eines Listenelementes</u>
     */
    id: string;
    /**
     * ###### List item text ###### <u>Text eines Listenelementes</u>
     */
    value: string;
    /**
     * ###### Fixed or unselectable property ###### <u>Unveränderliche oder nicht selektierbare Eigenschaft</u>
     */
    fixed?: boolean;
}

