/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationMetaDataDTO } from './validationMetaData.model';


/**
 * ###### Meta data ###### <u>Metadaten</u>
 */
export interface MetaDataDTO { 
    validation?: ValidationMetaDataDTO;
    /**
     * ###### Required property ###### <u>Erforderliche Eigenschaft</u>
     */
    required?: boolean;
    /**
     * ###### Fixed property ###### <u>Unveränderliche Eigenschaft</u>
     */
    fixed?: boolean;
}

