/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferODRequestDTO } from './offerODRequest.model';
import { OfferCalculationDTO } from './offerCalculation.model';


/**
 * ###### An offer contains all the necessary personal and tariff information for a calculation and the creation of a short proposal ###### <u>Ein Angebot enthält alle notwendigen persönlichen und tariflichen Angaben für eine Kalkulation und eine Erstellung eines Kurzangebots</u>
 */
export interface OfferCalculationODDTO extends OfferCalculationDTO { 
    offer: OfferODRequestDTO;
}

