/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonalDataODDTO } from './personalDataOD.model';
import { OfferResponseDTO } from './offerResponse.model';
import { ShortOfferDataDTO } from './shortOfferData.model';
import { TariffDataODDTO } from './tariffDataOD.model';
import { ProductDTO } from './product.model';
import { RiskDataDTO } from './riskData.model';


/**
 * ###### An offer contains all the necessary personal and tariff information for a calculation and the creation of a short proposal ###### <u>Ein Angebot enthält alle notwendigen persönlichen und tariflichen Angaben für eine Kalkulation und eine Erstellung eines Kurzangebots</u>
 */
export interface OfferODResponseDTO extends OfferResponseDTO { 
    /**
     * primary key
     */
    readonly id: number;
    /**
     * update timestamp
     */
    readonly update_date: string;
    /**
     * foreign key to process resource
     */
    process_id: number;
    product?: ProductDTO;
    tariff_data?: TariffDataODDTO;
    personal_data: PersonalDataODDTO;
    risk_data?: RiskDataDTO;
    short_offer_data?: ShortOfferDataDTO;
}

