/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OfferRequestDTO } from './offerRequest.model';
import { ShortOfferDataDTO } from './shortOfferData.model';
import { PersonalDataODRequestDTO } from './personalDataODRequest.model';
import { TariffDataODRequestDTO } from './tariffDataODRequest.model';
import { ProductDTO } from './product.model';
import { RiskDataDTO } from './riskData.model';


/**
 * ###### An offer contains all the necessary personal and tariff information for a calculation and the creation of a short proposal ###### <u>Ein Angebot enthält alle notwendigen persönlichen und tariflichen Angaben für eine Kalkulation und eine Erstellung eines Kurzangebots</u>
 */
export interface OfferODRequestDTO extends OfferRequestDTO { 
    /**
     * primary key
     */
    readonly id?: number;
    /**
     * update timestamp
     */
    update_date?: string;
    /**
     * foreign key to process resource
     */
    process_id: number;
    product?: ProductDTO;
    tariff_data?: TariffDataODRequestDTO;
    personal_data: PersonalDataODRequestDTO;
    risk_data?: RiskDataDTO;
    short_offer_data?: ShortOfferDataDTO;
}

