/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OfferCalculationDTO { 
    /**
     * Discriminator property
     */
    product_type: string;
    /**
     * ###### A flag to control if a validation without calculation should be performed ###### <u>Flag zu Steuerung, ob nur eine Validierung ohne Berechnung durchgeführt werden soll</u>
     */
    validation_only: boolean;
    /**
     * ###### A tariff attribute that is required for partial product validation ###### <u>Ein Tarifattribut, welches für eine partielle Produktvalidierung benötigt wird</u>
     */
    changed_attribute: string;
}

