/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonalDataValidationDTO } from './personalDataValidation.model';
import { OfferODRequestDTO } from './offerODRequest.model';


/**
 * ###### Personal data for validation ###### <u>Personendaten zur Validierung</u>
 */
export interface PersonalDataValidationODDTO extends PersonalDataValidationDTO { 
    offer: OfferODRequestDTO;
}

