/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonalDataValidationDTO { 
    /**
     * Discriminator property
     */
    product_type: string;
    /**
     * ###### A personal data attribute that is required for partial validation ###### <u>Ein Personendaten-Attribut, welches für eine partielle Validierung benötigt wird</u>
     */
    changed_attribute: string;
}

