/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListAttributeDTO } from './listAttribute.model';
import { BooleanAttributeDTO } from './booleanAttribute.model';
import { DoubleAttributeDTO } from './doubleAttribute.model';
import { PersonalDataResponseDTO } from './personalDataResponse.model';
import { DateAttributeDTO } from './dateAttribute.model';
import { PersonalDataProfessionalDataDTO } from './personalDataProfessionalData.model';


/**
 * ###### Short offer ###### <u>Angaben zum Kurzangebot</u> Persönliche Angaben zum Angebot
 */
export interface PersonalDataODDTO extends PersonalDataResponseDTO { 
    birth_date: DateAttributeDTO;
    gender?: ListAttributeDTO;
    gross_annual_income?: DoubleAttributeDTO;
    existing_insurances?: BooleanAttributeDTO;
    number_existing_insurances?: ListAttributeDTO;
    accumulated_annual_pensions?: DoubleAttributeDTO;
    smoker: BooleanAttributeDTO;
    professional_data: PersonalDataProfessionalDataDTO;
}

