/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListAttributeDTO } from './listAttribute.model';
import { BooleanAttributeDTO } from './booleanAttribute.model';
import { DoubleAttributeDTO } from './doubleAttribute.model';
import { BooleanAttributeRequiredDTO } from './booleanAttributeRequired.model';
import { DateAttributeRequiredDTO } from './dateAttributeRequired.model';
import { PersonalDataRequestDTO } from './personalDataRequest.model';
import { PersonalDataProfessionalDataRequestDTO } from './personalDataProfessionalDataRequest.model';
import { ListAttributeRequiredDTO } from './listAttributeRequired.model';


/**
 * ###### Short offer ###### <u>Angaben zum Kurzangebot</u> Persönliche Angaben zum Angebot
 */
export interface PersonalDataODRequestDTO extends PersonalDataRequestDTO { 
    birth_date: DateAttributeRequiredDTO;
    gender?: ListAttributeRequiredDTO;
    gross_annual_income?: DoubleAttributeDTO;
    existing_insurances?: BooleanAttributeDTO;
    number_existing_insurances?: ListAttributeDTO;
    accumulated_annual_pensions?: DoubleAttributeDTO;
    smoker: BooleanAttributeRequiredDTO;
    professional_data: PersonalDataProfessionalDataRequestDTO;
}

