/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListAttributeDTO } from './listAttribute.model';
import { StringAttributeDTO } from './stringAttribute.model';


/**
 * ###### Personal details ###### <u>Personenangaben</u>
 */
export interface Person1DTO { 
    given_name?: StringAttributeDTO;
    family_name?: StringAttributeDTO;
    salutation?: ListAttributeDTO;
}

