/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ###### Insurance product ###### <u>Versicherungsprodukt</u>
 */
export interface ProductDTO { 
    /**
     * ###### Product group ###### <u>Produktgruppe</u>
     */
    group: string;
    /**
     * ###### Product layer ###### <u>Schicht</u>
     */
    layer: string;
    /**
     * ###### Markteting name ###### <u>Marketingname</u>
     */
    marketing_name: string;
    /**
     * ###### Product name ###### <u>Produktname</u>
     */
    name: string;
    /**
     * ###### Tariff generation ###### <u>Tarifgeneration</u>
     */
    tariff_generation: string;
    /**
     * ###### Tariff abbreviation ###### <u>Tarifkürzel</u>
     */
    tariff: string;
}

