/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ###### Risk assessment ###### <u>Risikoprüfung</u>
 */
export interface RiskDataDTO { 
    /**
     * ###### Vote ###### <u>Votum</u>
     */
    vote?: string;
    /**
     * ###### Case-ID ###### <u>Case-ID</u>
     */
    case_id?: string;
}

