/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListAttributeDTO } from './listAttribute.model';
import { BooleanAttributeDTO } from './booleanAttribute.model';
import { ShortOfferPersonDTO } from './shortOfferPerson.model';


/**
 * ###### Short offer data ###### <u>Kurzangebotangaben</u>
 */
export interface ShortOfferDataDTO { 
    simple?: ListAttributeDTO;
    extended?: ListAttributeDTO;
    personalized?: BooleanAttributeDTO;
    alternative_policyholder?: ListAttributeDTO;
    policyholder?: ShortOfferPersonDTO;
    insured_person?: ShortOfferPersonDTO;
}

