/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationMetaDataDTO } from './validationMetaData.model';


/**
 * ###### String meta data ###### <u>String Metadaten</u>
 */
export interface StringMetaDataDTO { 
    /**
     * ###### Minimum length ###### <u>Min Länge</u>
     */
    minLength?: number;
    /**
     * ###### Maximum length ###### <u>Max Länge</u>
     */
    maxLength?: number;
    validation?: ValidationMetaDataDTO;
    /**
     * ###### Required property ###### <u>Erforderliche Eigenschaft</u>
     */
    required?: boolean;
    /**
     * ###### Fixed property ###### <u>Unveränderliche Eigenschaft</u>
     */
    fixed?: boolean;
}

