/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StringMetaDataDTO } from './stringMetaData.model';


/**
 * ###### String attribute including value and meta data ###### <u>String-Attribute inkl. Wert und Metadaten</u>
 */
export interface StringAttributeDTO { 
    value?: string | null;
    metadata: StringMetaDataDTO;
}

