/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BooleanAttributeRequiredDTO } from './booleanAttributeRequired.model';
import { ListAttributeRequiredDTO } from './listAttributeRequired.model';


/**
 * Dynamikoptionen
 */
export interface TariffDataDynamicOptionsDTO { 
    dynamic: BooleanAttributeRequiredDTO;
    percentage?: ListAttributeRequiredDTO;
}

