/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListAttributeDTO } from './listAttribute.model';
import { BooleanAttributeRequiredDTO } from './booleanAttributeRequired.model';
import { IntegerAttributeDTO } from './integerAttribute.model';


/**
 * Risikodaten
 */
export interface TariffDataRiskOptionsDTO { 
    risk_group?: ListAttributeDTO;
    risk_group_ratio?: IntegerAttributeDTO;
    risk_vote_available: BooleanAttributeRequiredDTO;
    risk_premium?: IntegerAttributeDTO;
}

