/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TariffDataCalculationResultDTO } from './tariffDataCalculationResult.model';
import { TariffDataRiskOptionsDTO } from './tariffDataRiskOptions.model';
import { TariffDataDynamicOptionsDTO } from './tariffDataDynamicOptions.model';
import { TariffDataOtherOptionsDTO } from './tariffDataOtherOptions.model';
import { TariffDataResponseDTO } from './tariffDataResponse.model';
import { TariffDataGeneralOptionsDTO } from './tariffDataGeneralOptions.model';


/**
 * ###### Data for an occupational disability tariff ###### <u>Daten für ein Berufsunfähigkeitstarif</u>
 */
export interface TariffDataODDTO extends TariffDataResponseDTO { 
    general_options: TariffDataGeneralOptionsDTO;
    dynamic_options: TariffDataDynamicOptionsDTO;
    other_options: TariffDataOtherOptionsDTO;
    risk_options: TariffDataRiskOptionsDTO;
    calculation_result?: TariffDataCalculationResultDTO;
}

