/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ###### General result data of a insurance calculation ###### <u>Allgemeine Ergebnisdaten der Kalkulation einer Versicherung</u>
 */
export interface TariffDataCalculationResultDTO { 
    /**
     * ###### Premium per collecting mode (net) ###### <u>Beitrag je Zahlweise (netto)</u>
     */
    premium_net: number;
    /**
     * ###### Premium per collecting mode (gross) ###### <u>Beitrag je Zahlweise (brutto)</u>
     */
    premium_gross: number;
    /**
     * ###### Pension (monthly) ###### <u>Rente (monatlich)</u>
     */
    pension: number;
}

