/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TariffDataCalculationResultDTO } from './tariffDataCalculationResult.model';
import { TariffDataDynamicOptionsRequestDTO } from './tariffDataDynamicOptionsRequest.model';
import { TariffDataOtherOptionsRequestDTO } from './tariffDataOtherOptionsRequest.model';
import { TariffDataRequestDTO } from './tariffDataRequest.model';
import { TariffDataRiskOptionsRequestDTO } from './tariffDataRiskOptionsRequest.model';
import { TariffDataGeneralOptionsRequestDTO } from './tariffDataGeneralOptionsRequest.model';


/**
 * ###### Data for an occupational disability tariff ###### <u>Daten für ein Berufsunfähigkeitstarif</u>
 */
export interface TariffDataODRequestDTO extends TariffDataRequestDTO { 
    general_options: TariffDataGeneralOptionsRequestDTO;
    dynamic_options: TariffDataDynamicOptionsRequestDTO;
    other_options: TariffDataOtherOptionsRequestDTO;
    risk_options: TariffDataRiskOptionsRequestDTO;
    calculation_result?: TariffDataCalculationResultDTO;
}

