/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntegerAttributeRequiredDTO } from './integerAttributeRequired.model';
import { ListAttributeDTO } from './listAttribute.model';
import { BooleanAttributeRequiredDTO } from './booleanAttributeRequired.model';
import { ListAttributeRequiredDTO } from './listAttributeRequired.model';


/**
 * Weitere Tarifoptionen
 */
export interface TariffDataOtherOptionsRequestDTO { 
    target_group_concept: ListAttributeRequiredDTO;
    rising_pension: BooleanAttributeRequiredDTO;
    rate_of_rising_pension?: ListAttributeDTO;
    benefit_during_sick_leave: BooleanAttributeRequiredDTO;
    grace_period: IntegerAttributeRequiredDTO;
}

