/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntegerAttributeRequiredDTO } from './integerAttributeRequired.model';
import { DoubleAttributeRequiredDTO } from './doubleAttributeRequired.model';
import { DateAttributeRequiredDTO } from './dateAttributeRequired.model';
import { ListAttributeRequiredDTO } from './listAttributeRequired.model';


/**
 * Allgemeine Tarifeingaben
 */
export interface TariffDataGeneralOptionsDTO { 
    start_of_insurance: DateAttributeRequiredDTO;
    final_insurance_age: IntegerAttributeRequiredDTO;
    benefit_expiration: ListAttributeRequiredDTO;
    benefit_expiration_date?: DateAttributeRequiredDTO;
    benefit_final_age: IntegerAttributeRequiredDTO;
    appropriation_of_surplus: ListAttributeRequiredDTO;
    contract_type: ListAttributeRequiredDTO;
    type_of_specification: ListAttributeRequiredDTO;
    premium_collecting_mode: ListAttributeRequiredDTO;
    value_of_specification?: DoubleAttributeRequiredDTO;
}

