/**
 * OfferService
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ###### Validation meta data ###### <u>Validierung Metadaten</u>
 */
export interface ValidationMetaDataDTO { 
    /**
     * ###### Validation message level ###### <u>Level der Validierungsnachricht</u>
     */
    msg_level: ValidationMetaDataDTOMsgLevelEnum;
    /**
     * ###### Validation message ###### <u>Validierungsnachricht</u>
     */
    msg: string;
}
export enum ValidationMetaDataDTOMsgLevelEnum {
    INFO = 'INFO',
    WARN = 'WARN',
    ERROR = 'ERROR'
};



